<#
    .SYNOPSIS
        A horrible script for creating the PSM1 files for this module by concatanating a series of .PS1 files together in a specific order

    .NOTES
        This is the worst code in the entire repository an should be shot with a canon as soon as possible.

        There is a short-coming in Powershell regarding how to handle class files. It's virtually impossible for
        a PS1 file containing classes to be loaded by another file... especially if that file is loaded by
        another file.

        To resolve this issue, I have made this script which first makes a PSM1 for each DSC resource that needs to
        include something. I then glue all the PSM1 files together into one giant PSM1 file because Import-Module
        acts really weird and won't find the other PSM1 files if they aren't part of the main PSM1 file.

        I would have written a nice clean function to do this job, but I hate the way this works and would
        rather make a script compiler.. possibly one that minimizes as well at a later point. So for now, I'll
        settle for this horrible slop.
#>

[string]$cUnattendXmlContent = @'
# ---------------------------------------------------------------------------------------------------
# DO NOT EDIT THIS FILE - THIS IS A GENERATED FILE
# ------
# This file is generated by HelperScripts/buildPSM.ps1 by combining the source files from the project
# into this one script.
# ---------------------------------------------------------------------------------------------------

'@

$cUnattendXmlContent += (Get-Content -Raw -Path (Join-Path -Path $PSScriptRoot -ChildPath '..\DSCResources\cUnattendXml\Classes\UnattendXml.ps1')).TrimEnd() + "`n"
$cUnattendXmlContent += (Get-Content -Raw -Path (Join-Path -Path $PSScriptRoot -ChildPath '..\DSCResources\cUnattendXml\Classes\cUnattendXml.ps1')).TrimEnd() + "`n"

Set-Content -Path (Join-Path -Path $PSScriptRoot -ChildPath '..\DSCResources\cUnattendXml\cUnattendXml.psm1') -Value $cUnattendXmlContent

[string]$cVHDFileSystemContent = @'
# ---------------------------------------------------------------------------------------------------
# DO NOT EDIT THIS FILE - THIS IS A GENERATED FILE
# ------
# This file is generated by HelperScripts/buildPSM.ps1 by combining the source files from the project
# into this one script.
# ---------------------------------------------------------------------------------------------------

'@

$cVHDFileSystemContent += (Get-Content -raw -Path (Join-Path -Path $PSScriptRoot -ChildPath '..\HelperScripts\MOFUtilities\parseMOF.ps1')) + "`n"
$cVHDFileSystemContent += (Get-Content -raw -Path (Join-Path -Path $PSScriptRoot -ChildPath '..\HelperScripts\MOFUtilities\cDSCResourceManifestItem.ps1')) + "`n" 
$cVHDFileSystemContent += (Get-Content -raw -Path (Join-Path -Path $PSScriptRoot -ChildPath '..\HelperScripts\MOFUtilities\cDSCResourceInformation.ps1')) + "`n"
$cVHDFileSystemContent += (Get-Content -raw -Path (Join-Path -Path $PSScriptRoot -ChildPath '..\HelperScripts\MOFUtilities\cOfflineMOFDependencyInstaller.ps1')) + "`n" 
$cVHDFileSystemContent += (Get-Content -Raw -Path (Join-Path -Path $PSScriptRoot -ChildPath '..\DSCResources\cVHDFileSystem\Classes\cVHDFileSystem.ps1')).TrimEnd() + "`n"

Set-Content -Path (Join-Path -Path $PSScriptRoot -ChildPath '..\DSCResources\cVHDFileSystem\cVHDFileSystem.psm1') -Value $cVHDFileSystemContent

[string]$content = @'
# ---------------------------------------------------------------------------------------------------
# DO NOT EDIT THIS FILE - THIS IS A GENERATED FILE
# ------
# This file is generated by HelperScripts/buildPSM.ps1 by combining the source files from the project
# into this one script.
# ---------------------------------------------------------------------------------------------------

'@

$content += (Get-Content -Raw -Path (Join-Path -Path $PSScriptRoot -ChildPath '..\DSCResources\cUnattendXml\cUnattendXml.psm1')).TrimEnd() + "`n"
$content += (Get-Content -Raw -Path (Join-Path -Path $PSScriptRoot -ChildPath '..\DSCResources\cDifferencingVHD\cDifferencingVHD.psm1')).TrimEnd() + "`n"
$content += (Get-Content -Raw -Path (Join-Path -Path $PSScriptRoot -ChildPath '..\DSCResources\cGuestRegistryKey\cGuestRegistryKey.psm1')).TrimEnd() + "`n"
$content += (Get-Content -Raw -Path (Join-Path -Path $PSScriptRoot -ChildPath '..\DSCResources\cVHDFileSystem\cVHDFileSystem.psm1')).TrimEnd() + "`n"
$content += (Get-Content -Raw -Path (Join-Path -Path $PSScriptRoot -ChildPath '..\DSCResources\cWindowsVHD\cWindowsVHD.psm1')).TrimEnd() + "`n"

Set-Content -Path (Join-Path -Path $PSScriptRoot -ChildPath '..\cDayZeroDeploy.psm1') -Value $content